### ISSUE TITLE
Damaged Configuration Settings Page

### ISSUE THREAD

**Issue by pozdeiev** [gerardnico/dokuwiki-plugin-minimap#2]
Hello.
Thank you for the plugin.
I have an issue: when the plugin is enabled, settings has such view:
![lblgak2l](https://cloud.githubusercontent.com/assets/16384176/11930450/86af40b0-a7f4-11e5-89c8-25c9813e0912.png)

**Comment by gerardnico** [comment]
Sorry for the convenience. As I use a bootstrap template, I didn't add this problem. Can you try to update the plugin and let me know if all is working as expected ? Thanks Nico
