### ISSUE TITLE
The page count shows one less than the actual number of pages

### ISSUE THREAD

**Issue by Daeron08** [gerardnico/dokuwiki-plugin-minimap#5]
Hey, thanks for the plugin.

It appears to me that the page count is currently incorrect. Take this page for example:
https://gerardnico.com/dokuwiki/minimap

It shows 19 pages, however there are actually 20 of them if you count the start page of the namespace (dokuwiki:dokuwiki).

Similarly, if you create a namespace that does not contain a start page, it will show one less than however many pages there are:
https://i.imgur.com/WKTYOSX.png

Additonally, any chance of implementing a setting which would disable the homepage check and the page count block altogether? Since I don't use homepages, I don't really benefit from it (and if there is a homepage, it could just be listed among the other pages in the list).

Thanks!

**Comment by gerardnico** [comment]
Hallo,

The algorithm is just doing a basic bad arithmetic such as total minus one as I have always expected a Home Page.  See: https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L248

The header build just above. If you suppress this line, it should disappear:
https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L250

Cheers
Nico

**Comment by Daeron08** [comment]
As a dirty fix starting the $pageNum = 0 (line 113) from 1 seemed to do the trick too in terms of page count. Ended up just suppressing the header altogether though, like you said.

Thanks for the plugin again.

**Comment by gerardnico** [comment]
Ok. If I made a new version, I will try to add this enhancement.

Have a nice weekend
Nico

**Comment by gerardnico** [comment]
This should be fixed. I have introduce the paramter `showHeader`. If you set to it to false, you got no header and therefore no error in the page count.
