### ISSUE TITLE
Syntax to show a specific namespace

### ISSUE THREAD

**Issue by vaniwiki** [gerardnico/dokuwiki-plugin-minimap#8]
Something like `<minimap @root>` to not show the current namespace, but a specified one.

My use case is that some of my namespaces have thousands of pages, and I'd rather have it just show the parent namespace's page index instead, by creating a new sidebar/minimap there.

**Comment by gerardnico** [comment]
You would like to have the namespace as a configuration. Am I right ?

`@root` is much more the namespace as defined here: https://www.dokuwiki.org/namespaces

**Comment by vaniwiki** [comment]
Well, my urls are like this: `book` and `book:chapter `and `book:chapter:page`, with no start pages apart from this. DokuWiki supports this as an alternative start page, and there are other plugins who respect that setting as well, so I thought it might not be too difficult to support.

**Comment by vaniwiki** [comment]
Ups I posted the previous comment in the wrong place. :)

**Comment by vaniwiki** [comment]
Often the minimap will show just the right amount of links, but sometimes... well, try having 6000+ links in your sidebar. So I thought it'd be good if I could make a sidebar in a namespace, and limit its minimap to that particular namespace, so sub namespaces will not expand further.

Sorry if my explanation isn't too good. Sometimes things make sense in my mind, but in reality...

**Comment by gerardnico** [comment]
I'm already using the dokuwiki function to get the namespace.

As you can see here:
https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L101

The getNs is the function used in Dokuwiki at:
https://github.com/splitbrain/dokuwiki/blob/master/inc/pageutils.php#L167

If you find me the function that used Dokuwiki to support what you say, I will replace it with pleasure.

Cheers
Nico

**Comment by gerardnico** [comment]
I needed to change the plugin because of a change in pcre2 in php7.3.

I have added a namespace parameter. May be this is what you wanted.
