### ISSUE TITLE
Incorrect date in plugin.info.txt

### ISSUE THREAD

**Issue by AnonTester** [gerardnico/dokuwiki-plugin-minimap#9]
The month and day in plugin.info.txt are swapped, causing issues with the update function in dokuwiki as after update to the latest version it still thinks an old version is installed.

date   2020-02-06
needs to be changed to:
date   2020-06-02

Thanks.

**Comment by gerardnico** [comment]
Men ... code is hard. 
I just change it in the commit #88cd33d

Thanks
